import 'react-native-get-random-values';
import {nanoid} from 'nanoid';

export const Employees = [
  {id: nanoid(), name: 'Macey Osaka'},
  {id: nanoid(), name: 'Amy Farha'},
  {id: nanoid(), name: 'Chris Jackson'},
  {id: nanoid(), name: 'Mia Smith'},
  {id: nanoid(), name: 'Atsuma Yami'},
  {id: nanoid(), name: 'Armanda Martin'},
  {id: nanoid(), name: 'Christy Thomas'},
  {id: nanoid(), name: 'Melissa Jones'},
  {id: nanoid(), name: 'Will Taylor'},
  {id: nanoid(), name: 'Jessica Ang'},
  {id: nanoid(), name: 'Kris Grey'},
  {id: nanoid(), name: 'Trish Kia'},
  {id: nanoid(), name: 'B'},
  {id: nanoid(), name: 'C'},
  {id: nanoid(), name: 'D'},
  {id: nanoid(), name: 'E'},
  {id: nanoid(), name: 'F'},
  {id: nanoid(), name: 'G'},
  {id: nanoid(), name: 'H'},
  {id: nanoid(), name: 'I'},
  {id: nanoid(), name: 'J'},
  {id: nanoid(), name: 'K'},
  {id: nanoid(), name: 'l'},
  {id: nanoid(), name: 'm'},
  {id: nanoid(), name: 'N'},
  {id: nanoid(), name: 'O'},
  {id: nanoid(), name: 'P'},
  {id: nanoid(), name: 'Q'},
  {id: nanoid(), name: 'R'},
  {id: nanoid(), name: 'B'},
];
